/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.vistas;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidad.control.AlumnoData;
import universidad.control.Conexion;
import universidad.control.CursadaData;
import universidad.control.MateriaData;
import universidad.modelo.Alumno;
import universidad.modelo.Cursada;
import universidad.modelo.Materia;

/**
 *
 * @author HP
 */
public class frmInscripcion extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private CursadaData cursadaData;
    
    private ArrayList<Alumno> listaAlumnos;
    private ArrayList<Materia> listaMaterias;
    private ArrayList<Cursada> listaCursada;
    
    private Conexion con;
    
    /**
     * Creates new form frmInscripcion
     */
    public frmInscripcion() {
        try {
            initComponents();
            con = new Conexion("jdbc:mariadb://localhost:3306/universidad", "root", "");
            modelo = new DefaultTableModel();
            
            alumnoData = new AlumnoData(con);
            listaAlumnos = (ArrayList)alumnoData.obtenerAlumnos();
            materiaData = new MateriaData(con);
            listaMaterias = (ArrayList)materiaData.obtenerMaterias();
            cursadaData = new CursadaData(con);
            listaCursada = (ArrayList)cursadaData.obtenerCursadas();
            
            cargarAlumnos();
            armarCabezeraTabla();
            cargarDatosTablaInscriptas();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCondicion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbInscriptas = new javax.swing.JRadioButton();
        rbNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();

        setClosable(true);
        setTitle("Inscripcion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Inscripción a Materias");

        jLabel2.setText("Alumno");

        cbxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setText("LISTADO DE MATERIAS");

        btgCondicion.add(rbInscriptas);
        rbInscriptas.setText("Inscriptas");
        rbInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInscriptasActionPerformed(evt);
            }
        });

        btgCondicion.add(rbNoInscriptas);
        rbNoInscriptas.setText("No Inscriptas");
        rbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoInscriptasActionPerformed(evt);
            }
        });

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMaterias);

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular Inscripcion");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rbInscriptas)
                        .addGap(18, 18, 18)
                        .addComponent(rbNoInscriptas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscribir)
                .addGap(68, 68, 68)
                .addComponent(btnAnular)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbInscriptas)
                    .addComponent(rbNoInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnular))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInscriptasActionPerformed
        // TODO add your handling code here:
        cargarDatosTablaInscriptas();
        this.btnInscribir.setEnabled(false);
        this.btnAnular.setEnabled(true);
    }//GEN-LAST:event_rbInscriptasActionPerformed

    private void rbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoInscriptasActionPerformed
        // TODO add your handling code here:
        cargarDatosTablaNoInscriptas();
        this.btnInscribir.setEnabled(true);
        this.btnAnular.setEnabled(false);
    }//GEN-LAST:event_rbNoInscriptasActionPerformed

    private void cbxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumnoActionPerformed
        if(rbInscriptas.isSelected()){
            cargarDatosTablaInscriptas();
        } else {
            cargarDatosTablaNoInscriptas();
        }
    }//GEN-LAST:event_cbxAlumnoActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        int fila = tblMaterias.getSelectedRow();
        
            if (fila != -1){
            Alumno al = (Alumno)cbxAlumno.getSelectedItem();
            
            int idMateria = (Integer)modelo.getValueAt(fila, 0);
            String nombreMateria = (String) modelo.getValueAt(fila, 1);
            Materia m = new Materia(idMateria, nombreMateria);
            
            Cursada c = new Cursada(al, m, 0);
            CursadaData cd = new CursadaData(con);
            cd.guardarCursada(c);
            }
            cargarDatosTablaNoInscriptas();
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
         int fila = tblMaterias.getSelectedRow();
         
         if(fila != -1){
             Alumno al = (Alumno)cbxAlumno.getSelectedItem();
             
            int idMateria = (Integer)modelo.getValueAt(fila, 0);
            String nombreMateria = (String) modelo.getValueAt(fila, 1);
            Materia m = new Materia(idMateria, nombreMateria);
            
            CursadaData cd = new CursadaData(con);
            cd.borrarCursadaDeUnaMateriaDeunAlumno(al.getId(), m.getId());
            
         }
         cargarDatosTablaInscriptas();
    }//GEN-LAST:event_btnAnularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCondicion;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JComboBox<Alumno> cbxAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbInscriptas;
    private javax.swing.JRadioButton rbNoInscriptas;
    private javax.swing.JTable tblMaterias;
    // End of variables declaration//GEN-END:variables

    private void cargarAlumnos() {
        for(Alumno item:listaAlumnos) {
            this.cbxAlumno.addItem(item);
        }
        rbInscriptas.setSelected(true);
    }

    private void armarCabezeraTabla() {
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("MATERIA");
        for(Object it:columnas) {
            modelo.addColumn(it);
        }
        this.tblMaterias.setModel(modelo);
    }
    
    private void borrarFilasTabla() {
        int f = this.modelo.getRowCount() - 1;
        for (int i=f; i>=0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDatosTablaInscriptas() {
        borrarFilasTabla();
        
        Alumno al = (Alumno)this.cbxAlumno.getSelectedItem();
        listaMaterias = (ArrayList)cursadaData.obtenerMateriasCursadas(al.getId());
        for(Materia m:listaMaterias) {
            modelo.addRow(new Object[]{m.getId(), m.getNombre()});
        }
    }

    private void cargarDatosTablaNoInscriptas() {
        borrarFilasTabla();
        
        Alumno al = (Alumno)this.cbxAlumno.getSelectedItem();
        listaMaterias = (ArrayList)cursadaData.obtenerMateriasNOCursadas(al.getId());
        for(Materia m:listaMaterias) {
            modelo.addRow(new Object[]{m.getId(), m.getNombre()});
        }
    }
    private void cargarDatosTabla(){
        
    }
}
